-- MySQL Script generated by MySQL Workbench
-- Пн 01 апр 2019 19:19:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd3`;

-- -----------------------------------------------------
-- Schema bd3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd3` DEFAULT CHARACTER SET utf8;
USE `bd3`;

-- -----------------------------------------------------
-- Table `bd3`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd3`.`user`
(
    `id`          INT          NOT NULL AUTO_INCREMENT,
    `login`       VARCHAR(45)  NULL,
    `passwd`      VARCHAR(45)  NULL,
    `first_name`  VARCHAR(60)  NOT NULL,
    `middle_name` VARCHAR(60)  NULL,
    `last_name`   VARCHAR(60)  NOT NULL,
    `email`       VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd3`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd3`.`group`
(
    `id`      INT         NOT NULL AUTO_INCREMENT,
    `user_id` INT         NOT NULL,
    `name`    VARCHAR(60) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_group_user1_idx` (`user_id` ASC),
    CONSTRAINT `fk_group_user1`
        FOREIGN KEY (`user_id`)
            REFERENCES `bd3`.`user` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd3`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd3`.`contact`
(
    `id`              INT          NOT NULL AUTO_INCREMENT,
    `user_id`         INT          NOT NULL,
    `first_name`      VARCHAR(60)  NOT NULL,
    `middle_name`     VARCHAR(60)  NULL,
    `last_name`       VARCHAR(60)  NOT NULL,
    `email`           VARCHAR(255) NOT NULL,
    `tel`             VARCHAR(11)  NOT NULL,
    `sending_counter` INT          NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_contact_user1_idx` (`user_id` ASC),
    CONSTRAINT `fk_contact_user1`
        FOREIGN KEY (`user_id`)
            REFERENCES `bd3`.`user` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd3`.`distributionChannel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd3`.`distributionChannel`
(
    `id`   INT         NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(60) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd3`.`contact_distributionChannel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd3`.`contact_distributionChannel`
(
    `contact_id`             INT          NOT NULL,
    `distributionChannel_id` INT          NOT NULL,
    `token`                  VARCHAR(255) NULL,
    PRIMARY KEY (`contact_id`, `distributionChannel_id`),
    INDEX `fk_contact_has_distributionChannel_distributionChannel1_idx` (`distributionChannel_id` ASC),
    INDEX `fk_contact_has_distributionChannel_contact_idx` (`contact_id` ASC),
    CONSTRAINT `fk_contact_has_distributionChannel_contact`
        FOREIGN KEY (`contact_id`)
            REFERENCES `bd3`.`contact` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_contact_has_distributionChannel_distributionChannel1`
        FOREIGN KEY (`distributionChannel_id`)
            REFERENCES `bd3`.`distributionChannel` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd3`.`contact_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd3`.`contact_group`
(
    `contact_id` INT NOT NULL,
    `group_id`   INT NOT NULL,
    PRIMARY KEY (`contact_id`, `group_id`),
    INDEX `fk_contact_has_group_group1_idx` (`group_id` ASC),
    INDEX `fk_contact_has_group_contact1_idx` (`contact_id` ASC),
    CONSTRAINT `fk_contact_has_group_contact1`
        FOREIGN KEY (`contact_id`)
            REFERENCES `bd3`.`contact` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_contact_has_group_group1`
        FOREIGN KEY (`group_id`)
            REFERENCES `bd3`.`group` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
