INSERT INTO `carconst`.`complectation_power` (`id`, `complectation_id`, `power_id`) VALUES ('1', '1', '2');
INSERT INTO `carconst`.`complectation_power` (`id`, `complectation_id`, `power_id`) VALUES ('2', '1', '1');
INSERT INTO `carconst`.`complectation_power` (`id`, `complectation_id`, `power_id`) VALUES ('3', '2', '5');
INSERT INTO `carconst`.`complectation_power` (`id`, `complectation_id`, `power_id`) VALUES ('4', '2', '4');
INSERT INTO `carconst`.`complectation_power` (`id`, `complectation_id`, `power_id`) VALUES ('5', '3', '5');
INSERT INTO `carconst`.`complectation_power` (`id`, `complectation_id`, `power_id`) VALUES ('6', '3', '4');
INSERT INTO `carconst`.`complectation_power` (`id`, `complectation_id`, `power_id`) VALUES ('7', '4', '5');
INSERT INTO `carconst`.`complectation_power` (`id`, `complectation_id`, `power_id`) VALUES ('8', '4', '4');
INSERT INTO `carconst`.`complectation_power` (`id`, `complectation_id`, `power_id`) VALUES ('9', '4', '3');
