-- MySQL Script generated by MySQL Workbench
-- Wed 06 Mar 2019 16:29:45 MSK
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema autocalk
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `autocalk` ;

-- -----------------------------------------------------
-- Schema autocalk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autocalk` DEFAULT CHARACTER SET utf8 ;
USE `autocalk` ;

-- -----------------------------------------------------
-- Table `autocalk`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autocalk`.`series` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `img` VARCHAR(255) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autocalk`.`bodytype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autocalk`.`bodytype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autocalk`.`power`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autocalk`.`power` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autocalk`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autocalk`.`color` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autocalk`.`furnish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autocalk`.`furnish` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `img` VARCHAR(255) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autocalk`.`dop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autocalk`.`dop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `img` VARCHAR(255) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
