-- MySQL Script generated by MySQL Workbench
-- Mon 15 Apr 2019 13:43:59 MSK
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yabs_v0.3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `yabs_v0.3` ;

-- -----------------------------------------------------
-- Schema yabs_v0.3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yabs_v0.3` DEFAULT CHARACTER SET utf8 ;
USE `yabs_v0.3` ;

-- -----------------------------------------------------
-- Table `yabs_v0.3`.`card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yabs_v0.3`.`card` ;

CREATE TABLE IF NOT EXISTS `yabs_v0.3`.`card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num` INT NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `middle_name` VARCHAR(255) NULL,
  `birthday` DATE NOT NULL,
  `phone_number` VARCHAR(11) NOT NULL,
  `bonus` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `discount` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `turnover_amount` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `status` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `num_UNIQUE` (`num` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yabs_v0.3`.`bonus_rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yabs_v0.3`.`bonus_rules` ;

CREATE TABLE IF NOT EXISTS `yabs_v0.3`.`bonus_rules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `purchase_amount` DECIMAL(10,2) NOT NULL,
  `bonus` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yabs_v0.3`.`celebration_day`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yabs_v0.3`.`celebration_day` ;

CREATE TABLE IF NOT EXISTS `yabs_v0.3`.`celebration_day` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `factor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yabs_v0.3`.`auth_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yabs_v0.3`.`auth_users` ;

CREATE TABLE IF NOT EXISTS `yabs_v0.3`.`auth_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `middle_name` VARCHAR(255) NULL,
  `birthday` DATE NULL,
  `phone_number` VARCHAR(11) NOT NULL,
  `position` VARCHAR(255) NOT NULL,
  `passhash` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yabs_v0.3`.`history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yabs_v0.3`.`history` ;

CREATE TABLE IF NOT EXISTS `yabs_v0.3`.`history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  `card_num` INT NULL DEFAULT NULL,
  `operation_type` VARCHAR(255) NOT NULL,
  `operation_amount` DECIMAL(10,2) NULL,
  `body` TEXT NOT NULL,
  `created_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yabs_v0.3`.`discount_rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yabs_v0.3`.`discount_rules` ;

CREATE TABLE IF NOT EXISTS `yabs_v0.3`.`discount_rules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `turnover_amount` DECIMAL(10,2) NOT NULL,
  `discount` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `yabs_v0.3`.`new_card_rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yabs_v0.3`.`new_card_rules` ;

CREATE TABLE IF NOT EXISTS `yabs_v0.3`.`new_card_rules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `value` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `yabs_v0.3`.`bonus_rules`
-- -----------------------------------------------------
START TRANSACTION;
USE `yabs_v0.3`;
INSERT INTO `yabs_v0.3`.`bonus_rules` (`id`, `purchase_amount`, `bonus`) VALUES (1, 500, 30);
INSERT INTO `yabs_v0.3`.`bonus_rules` (`id`, `purchase_amount`, `bonus`) VALUES (2, 1000, 80);
INSERT INTO `yabs_v0.3`.`bonus_rules` (`id`, `purchase_amount`, `bonus`) VALUES (3, 2000, 200);
INSERT INTO `yabs_v0.3`.`bonus_rules` (`id`, `purchase_amount`, `bonus`) VALUES (4, 3000, 300);
INSERT INTO `yabs_v0.3`.`bonus_rules` (`id`, `purchase_amount`, `bonus`) VALUES (5, 4000, 400);
INSERT INTO `yabs_v0.3`.`bonus_rules` (`id`, `purchase_amount`, `bonus`) VALUES (6, 5000, 500);
INSERT INTO `yabs_v0.3`.`bonus_rules` (`id`, `purchase_amount`, `bonus`) VALUES (7, 10000, 1500);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yabs_v0.3`.`celebration_day`
-- -----------------------------------------------------
START TRANSACTION;
USE `yabs_v0.3`;
INSERT INTO `yabs_v0.3`.`celebration_day` (`id`, `date`, `name`, `factor`) VALUES (1, '2019-01-01', 'Новогодние каникулы', 2);
INSERT INTO `yabs_v0.3`.`celebration_day` (`id`, `date`, `name`, `factor`) VALUES (2, '2019-01-02', 'Новогодние каникулы', 2);
INSERT INTO `yabs_v0.3`.`celebration_day` (`id`, `date`, `name`, `factor`) VALUES (3, '2019-01-03', 'Новогодние каникулы', 2);
INSERT INTO `yabs_v0.3`.`celebration_day` (`id`, `date`, `name`, `factor`) VALUES (4, '2019-01-04', 'Новогодние каникулы', 2);
INSERT INTO `yabs_v0.3`.`celebration_day` (`id`, `date`, `name`, `factor`) VALUES (5, '2019-01-05', 'Новогодние каникулы', 2);
INSERT INTO `yabs_v0.3`.`celebration_day` (`id`, `date`, `name`, `factor`) VALUES (6, '2019-01-06', 'Новогодние каникулы', 2);
INSERT INTO `yabs_v0.3`.`celebration_day` (`id`, `date`, `name`, `factor`) VALUES (7, '2019-01-08', 'Новогодние каникулы', 2);
INSERT INTO `yabs_v0.3`.`celebration_day` (`id`, `date`, `name`, `factor`) VALUES (8, '2019-01-07', 'Рождество Христово', 2);
INSERT INTO `yabs_v0.3`.`celebration_day` (`id`, `date`, `name`, `factor`) VALUES (9, '2019-02-23', 'День защитника Отечества', 2);
INSERT INTO `yabs_v0.3`.`celebration_day` (`id`, `date`, `name`, `factor`) VALUES (10, '2019-03-08', 'Международный женский день', 2);
INSERT INTO `yabs_v0.3`.`celebration_day` (`id`, `date`, `name`, `factor`) VALUES (11, '2019-05-01', 'Праздник Весны и Труда', 2);
INSERT INTO `yabs_v0.3`.`celebration_day` (`id`, `date`, `name`, `factor`) VALUES (12, '2019-05-09', 'День Победы', 2);
INSERT INTO `yabs_v0.3`.`celebration_day` (`id`, `date`, `name`, `factor`) VALUES (13, '2019-06-12', 'День России', 2);
INSERT INTO `yabs_v0.3`.`celebration_day` (`id`, `date`, `name`, `factor`) VALUES (14, '2019-11-04', 'День народного единства', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yabs_v0.3`.`auth_users`
-- -----------------------------------------------------
START TRANSACTION;
USE `yabs_v0.3`;
INSERT INTO `yabs_v0.3`.`auth_users` (`id`, `login`, `last_name`, `first_name`, `middle_name`, `birthday`, `phone_number`, `position`, `passhash`, `create_time`, `update_time`) VALUES (DEFAULT, 'man1', 'Джон', 'Сноу', NULL, '1995-04-12', '79785552211', 'manager', '$2y$10$0fkWqfdmNciRZMZ0yEe7OuvqGXK3yb/oSWPjWZKW..D6txT.VOGjC', '20190412093325', '20190412093325');

COMMIT;


-- -----------------------------------------------------
-- Data for table `yabs_v0.3`.`discount_rules`
-- -----------------------------------------------------
START TRANSACTION;
USE `yabs_v0.3`;
INSERT INTO `yabs_v0.3`.`discount_rules` (`id`, `turnover_amount`, `discount`) VALUES (1, 5000, 7.5);
INSERT INTO `yabs_v0.3`.`discount_rules` (`id`, `turnover_amount`, `discount`) VALUES (2, 10000, 10);
INSERT INTO `yabs_v0.3`.`discount_rules` (`id`, `turnover_amount`, `discount`) VALUES (3, 30000, 15);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yabs_v0.3`.`new_card_rules`
-- -----------------------------------------------------
START TRANSACTION;
USE `yabs_v0.3`;
INSERT INTO `yabs_v0.3`.`new_card_rules` (`id`, `name`, `value`) VALUES (1, 'bonus', 100);
INSERT INTO `yabs_v0.3`.`new_card_rules` (`id`, `name`, `value`) VALUES (2, 'discount', 5);

COMMIT;

