-- MySQL Script generated by MySQL Workbench
-- Tue 05 Mar 2019 11:00:35 MSK
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema carconst
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `carconst` ;

-- -----------------------------------------------------
-- Schema carconst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carconst` DEFAULT CHARACTER SET utf8 ;
USE `carconst` ;

-- -----------------------------------------------------
-- Table `carconst`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carconst`.`model` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `img` VARCHAR(255) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carconst`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carconst`.`series` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `img` VARCHAR(255) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carconst`.`bodytype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carconst`.`bodytype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `img` VARCHAR(255) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carconst`.`power`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carconst`.`power` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carconst`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carconst`.`color` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carconst`.`furnish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carconst`.`furnish` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `img` VARCHAR(255) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carconst`.`dop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carconst`.`dop` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `img` VARCHAR(255) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dop_model1_idx` (`model_id` ASC),
  CONSTRAINT `fk_dop_model1`
    FOREIGN KEY (`model_id`)
    REFERENCES `carconst`.`model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carconst`.`complectation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carconst`.`complectation` (
  `id` INT NOT NULL,
  `model_id` INT NOT NULL,
  `series_id` INT NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_model_series_model_idx` (`model_id` ASC),
  INDEX `fk_model_series_series1_idx` (`series_id` ASC),
  CONSTRAINT `fk_model_series_model`
    FOREIGN KEY (`model_id`)
    REFERENCES `carconst`.`model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_model_series_series1`
    FOREIGN KEY (`series_id`)
    REFERENCES `carconst`.`series` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carconst`.`complectation_bodytype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carconst`.`complectation_bodytype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `complectation_id` INT NOT NULL,
  `bodytype_id` INT NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_complectation_bodytype_complectation1_idx` (`complectation_id` ASC),
  INDEX `fk_complectation_bodytype_bodytype1_idx` (`bodytype_id` ASC),
  CONSTRAINT `fk_complectation_bodytype_complectation1`
    FOREIGN KEY (`complectation_id`)
    REFERENCES `carconst`.`complectation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_complectation_bodytype_bodytype1`
    FOREIGN KEY (`bodytype_id`)
    REFERENCES `carconst`.`bodytype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carconst`.`complectation_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carconst`.`complectation_color` (
  `id` INT NOT NULL,
  `color_id` INT NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  `complectation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_complectation_color_color1_idx` (`color_id` ASC),
  INDEX `fk_complectation_color_complectation1_idx` (`complectation_id` ASC),
  CONSTRAINT `fk_complectation_color_color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `carconst`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_complectation_color_complectation1`
    FOREIGN KEY (`complectation_id`)
    REFERENCES `carconst`.`complectation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carconst`.`complectation_furnish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carconst`.`complectation_furnish` (
  `id` INT NOT NULL,
  `complectation_id` INT NOT NULL,
  `furnish_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_complectation_furnish_complectation1_idx` (`complectation_id` ASC),
  INDEX `fk_complectation_furnish_furnish1_idx` (`furnish_id` ASC),
  CONSTRAINT `fk_complectation_furnish_complectation1`
    FOREIGN KEY (`complectation_id`)
    REFERENCES `carconst`.`complectation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_complectation_furnish_furnish1`
    FOREIGN KEY (`furnish_id`)
    REFERENCES `carconst`.`furnish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carconst`.`complectation_power`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carconst`.`complectation_power` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `complectation_id` INT NOT NULL,
  `power_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_complectation_power_complectation1_idx` (`complectation_id` ASC),
  INDEX `fk_complectation_power_power1_idx` (`power_id` ASC),
  CONSTRAINT `fk_complectation_power_complectation1`
    FOREIGN KEY (`complectation_id`)
    REFERENCES `carconst`.`complectation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_complectation_power_power1`
    FOREIGN KEY (`power_id`)
    REFERENCES `carconst`.`power` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
